server:
  port: 9089
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://35.240.226.176:5432/travelmarketplace
    username: postgres
    password: capstonevlu
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
